# Generated by Django 2.0.7 on 2018-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
