# Generated by Django 2.0.7 on 2018-12-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doc',
            field=models.FileField(upload_to='IMMP/projects/'),
        ),
    ]
